version: '3.8'

services:
  n8n:
    image: n8nio/n8n
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD=n8n_password
    ports:
      - "0.0.0.0:5678:5678" # Expose n8n on all network interfaces
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - app_network

  baserow:
    image: baserow/baserow
    environment:
      - DATABASE_URL=postgres://baserow:baserow_password@postgres:5432/baserow
    volumes:
      - baserow_data:/baserow/media
    networks:
      - app_network

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=n8n
      - POSTGRES_PASSWORD=n8n_password
      - POSTGRES_DB=n8n
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  kobold:
    image: kobold/kobold
    volumes:
      - kobold_data:/app/data
    networks:
      - app_network

  matrix:
    image: matrixdotorg/synapse
    environment:
      - SYNAPSE_SERVER_NAME=your.server.name
      - SYNAPSE_REPORT_STATS=yes
    volumes:
      - matrix_data:/data
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  n8n_data:
  baserow_data:
  postgres_data:
  kobold_data:
  matrix_data: